import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Analytics } from "@vercel/analytics/react"
import { ClerkProvider } from '@clerk/nextjs'
import { SignedIn, SignedOut } from '@clerk/nextjs';
import { auth } from '@clerk/nextjs/server';

import './globals.css'

import { Meal } from './_lib/definitions';
import { fetchMeals } from './_lib/data';
import Header from './_components/Header';
import Footer from './_components/Footer';
import LandingPage from './_components/LandingPage';

import ReactQueryProvider from './utils/ReactQueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'meal spark',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const meals: Meal[] = await fetchMeals();
  const { userId } = auth();

  return (
    <ReactQueryProvider>
      <ClerkProvider>
        <html lang="en" data-theme='cmyk'>
          <body className={`${inter.className} antialiased`}>
            <div className='w-full h-full flex flex-col'>
              <div className='flex justify-center mt-4 md:mt-6'>
                <Header userId={userId} meals={meals}/>
              </div>
              <div>
                <SignedIn>
                  {children}
                </SignedIn>
                <SignedOut>
                  <div className='flex justify-center items-center w-full h-full'>
                    <LandingPage />
                  </div>
                </SignedOut>
              </div>
              <div className='h-full w-full mt-10'>
                  <Footer />
              </div>
            </div>
            <Analytics />
          </body>
        </html>
      </ClerkProvider>
    </ReactQueryProvider>
  )
}
